// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xefwiadqkdtnuwgdlbov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZndpYWRxa2R0bnV3Z2RsYm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzUxMzAsImV4cCI6MjA2ODQxMTEzMH0.mXr5mVX6jTrNTXOzvh9Owo9knbIS4PPQQP98pnY0m9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});